# Generated by Django 2.1.7 on 2019-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20190615_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='update_time',
            field=models.DateTimeField(default='2019-06-15 12:45:40.948578'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(default='2019-06-15 12:45:40.948578'),
            preserve_default=False,
        ),
    ]
